---
version: 2
jobs:
  build:
    working_directory: /cli
    docker:
      - image: node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v0-yarn-{{ .Branch }}-{{checksum "yarn.lock"}}
            - v0-yarn-{{ .Branch }}
            - v0-yarn-master
      - run: yarn
      - run: {command: "./node_modules/.bin/tsc", when: always}
      - run: {command: "./node_modules/.bin/tslint --project .", when: always}
      - run: {command: "./node_modules/.bin/jest --coverage", when: always}
      - run: {command: "bash <(curl -s https://codecov.io/bash)"}
      - save_cache:
          key: v0-yarn-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - /cli/node_modules
            - /usr/local/share/.cache/yarn
