name: CI

on: [push]

jobs:
  ubuntu:
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install & test
      run: |
        yarn
        yarn add -D nyc@13 @oclif/nyc-config@1
        $NYC yarn test
        $NYC report --reporter text-lcov > coverage.lcov
        curl -s https://codecov.io/bash | bash
      env:
        CI: true
        NYC: "yarn exec nyc -- --nycrc-path node_modules/@oclif/nyc-config/.nycrc"
  windows:
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install & test
      run: |
        yarn
        yarn test
      env:
        CI: true
